### ISSUE TITLE
#ASK Tentang Table user_has_role

### ISSUE THREAD

**Issue by memcaliber** [Mamena2020/nodemi#13]
Maaf Om.. ijin bertanya lagi..
Tentang table default yang ada, **user_has_role**

Saya ingin menanyakan tentang table ini dan kolom **roleable_id**
![database_Tabel](https://github.com/Mamena2020/nodemi/assets/17555144/4b4b7fe9-f663-4e79-bb93-72d8aea909bc)

Apakah table ini maksudnya akan menjadi acuan seorang user terkait dengan roles tertentu? semacam junction table.
dan table roleable_id adalah akan terisi oleh id role dari table roles?

Terimakasih untuk jawabannya. 🙏

**Comment by Mamena2020** [comment]
@memcaliber  Untuk semua tabel yang berrelasi dengan tabel roles, menggunakan <a href='https://sequelize.org/docs/v6/advanced-association-concepts/polymorphic-associations/'> `polymorphic relation` </a> , dengan perantaranya adalah tabel `user_has_roles`.
Tujuannya agar tabel roles tidak berrelasi dengan 1 tabel saja, tapi dapat berrelasi dengan tabel apapun ketika si `coder` membinding model tertentu menggunakan fungsi  <a href='https://github.com/Mamena2020/nodemi/#role-and-permissions'> hasRole(YourModel) </a> maka model tersebut akan memiliki ability untuk set role menggunakan pemanggilan fungsi 
<a href='https://github.com/Mamena2020/nodemi/#set-users-role'> `instance.setRole(params)` </a>.
ex:

1. 
``` js

   const loadModels = async () => {
      await UserAdmin.sync() // model user admin
      await hasRole(UserAdmin) // membinding ke roles via table user_has_roles
```
maka data yang tersimpan di database setelah menggunakan setRole `await userAdmin.setRole('super_admin')`
``` 
   role_id => id dari tabel roles.
   roleable_id => id dari tabel user_admins
   roleable_type => nama model 'UserAdmin'
```
2. 
``` js

   const loadModels = async () => {
      await UserAdmin.sync() // model user admin
      await hasRole(UserAdmin) // membinding ke roles via table user_has_roles
     
      await UserCustomer.sync() // model user customer
      await hasRole(UserCustomer) // membinding ke roles via table user_has_roles
     
```
maka data yang tersimpan di database setelah menggunakan setRole `await userCustomer.setRole('customer_type_x')`
``` 
   role_id => id dari tabel roles.
   roleable_id => id dari tabel user_customers
   roleable_type => nama model 'UserCustomer'
```
Boilerplate ini mengunakan ORM Sequelize, jd untuk lebih jelasnya mengenai polymorphic relasi bisa <a href='https://sequelize.org/docs/v6/advanced-association-concepts/polymorphic-associations/'> cek ini </a>,
