### ISSUE TITLE
User Role & Permissions

### ISSUE THREAD

**Issue by syahrulright** [Mamena2020/nodemi#4]
Great project!
Ijin bertanya gan, saya sedang mencoba project agan ini, pas awal saya register user tidak langsung diberi role default kah? Semisal user yang saat pertama kali mendaftar diberi role "Customer" dan permissions secara default.
Apakah tidak ada pemberian role & permissions secara langsung secara default?
Terimakasih..

**Comment by Mamena2020** [comment]
@syahrulright 

Secara default role dan permission belum terisi.
Harus di isi dahulu dengan seeder.
```
   cli command: npx nodemi seed:run
```
command tersebut akan menjalankan seeder di `core/seeder/Seeder.js`,
sehingga bisa dipakai untuk mengisi role dan permission awal.
dapat dimodifikasi sesuai kebutuhan.

```
    const Seeder = async () => {
    
        let alreadySeed = await Permission.findAll()
    
        if (alreadySeed.length > 0) {
            console.log("already Seeding")
            return
        }
    
        for (let permission of permissions) {
            console.log(permission)
            await Permission.create({ name: permission })
        }
    
        await Role.bulkCreate(roles)
    
        let admin = await Role.findOne({ where: { name: "admin" } })
        if (admin) {
            await admin.assignPermissions(permissions)
        }
    
        let customer = await Role.findOne({ where: { name: "customer" } })
        if (customer) {
            await customer.assignPermissions([
                "user-create", "user-stored",
            ])
        }
    
    }
```

**Comment by syahrulright** [comment]
Nice one!
